export const portfolioItems = [
    {
        page: 'https://jorge-caceres-tp.netlify.app/',
        github: 'https://github.com/jaco9419/tu-vivero',
        title: 'Tu Vivero',
        description: 'HTML, CSS, Javascript',
        src: 'img/11.PNG',
    },
    {
        page: 'https://api-gallery.netlify.app/',
        github: 'https://github.com/jaco9419/Ejercicio-React',
        title: 'API Gallery',
        description: 'React, API, CSS, Dark Mode',
        src: 'img/12.PNG',
    },
    {
        page: 'https://jaco9419.github.io/Netflix-Land-Page/',
        title: 'Netflix Land Page',
        github: 'https://github.com/jaco9419/Netflix-Land-Page',
        description: 'HTML, CSS, Javascript',
        src: 'img/8.PNG',
    },
    {
        page: "https://jaco9419.github.io/Snake-Game/",
        github: 'https://github.com/jaco9419/Snake-Game',
        title: 'Snake Game',
        description: 'Canvas, CSS, Javascript, HTML',
        src: 'img/1.PNG',
    },
    {
        page: 'https://codepen.io/jaco-9419/full/vYOgzde',
        codepen: 'https://codepen.io/jaco-9419/pen/vYOgzde',
        title: 'Pomodoro Clock',
        description: 'React, HTML, CSS, Javascript',
        src: 'img/2.PNG',
    },
    {
        page: 'https://codepen.io/jaco-9419/full/poJRvVz',
        codepen: 'https://codepen.io/jaco-9419/pen/poJRvVz',
        title: 'Calculator',
        description: 'React, CSS, Javascript',
        src: 'img/3.PNG',
    },
    {
        page: 'https://codepen.io/jaco-9419/full/oNXYQXK',
        codepen: 'https://codepen.io/jaco-9419/pen/oNXYQXK',
        title: 'Drum App',
        description: 'React, CSS, Javascript',
        src: 'img/4.PNG',
    },
    {
        page: 'https://jaco9419.github.io/tic-tac-toe-2/',
        github: 'https://github.com/jaco9419/tic-tac-toe-2',
        title: 'Tic-tac-toe',
        description: 'React, CSS, Javascript',
        src: 'img/6.PNG',
    },
    {
        page: 'https://jaco9419.github.io/US-GDP/',
        github: 'https://github.com/jaco9419/US-GDP',
        title: 'US GDP Bar Chart',
        description: 'D3, CSS, Javascript',
        src: 'img/10.PNG',
    },
    {
        page: 'https://codepen.io/jaco-9419/full/xxbvJwv',
        codepen: 'https://codepen.io/jaco-9419/pen/xxbvJwv',
        title: 'Random Quote Generator',
        description: 'jQuery, CSS, Javascript',
        src: 'img/5.PNG',
    },
    {
        page: 'https://codepen.io/jaco-9419/full/qKPaoa',
        codepen: 'https://codepen.io/jaco-9419/pen/qKPaoa',
        title: 'Get Fluent Landing Page',
        description: 'Parallax, HTML, CSS, Javascript',
        src: 'img/7.PNG',
    },
]

